services:
- type: web
  name: selfy-lol
  env: node
  plan: free
  branch: main
  buildCommand: npm run build
  startCommand: npm run start
  autoDeploy: true
  envVars:
    - key: NODE_ENV
      value: production